const supportedTypes = {
  // ==================== TEXT FORMATS ====================
  "text/plain": ["txt", "text", "log", "md", "markdown", "readme", "license", "changelog"],
  "text/html": ["html", "htm", "shtml"],
  "text/css": ["css"],
  "text/javascript": ["js", "mjs", "jsm"],
  "text/typescript": ["ts"],
  "text/jsx": ["jsx"],
  "text/tsx": ["tsx"],
  "text/xml": ["xml", "xsl", "xsd"],
  "text/csv": ["csv"],
  "text/tab-separated-values": ["tsv"],
  "text/rtf": ["rtf"],
  "text/calendar": ["ics", "ifb"],
  "text/vcard": ["vcf", "vcard"],
  "text/yaml": ["yaml", "yml"],
  "text/x-python": ["py", "pyw"],
  "text/x-java-source": ["java"],
  "text/x-c": ["c", "h"],
  "text/x-c++": ["cpp", "cxx", "cc", "hpp", "hxx"],
  "text/x-csharp": ["cs"],
  "text/x-php": ["php", "phtml"],
  "text/x-ruby": ["rb", "rbw"],
  "text/x-perl": ["pl", "pm"],
  "text/x-shell": ["sh", "bash", "zsh", "fish"],
  "text/x-sql": ["sql"],
  "text/x-go": ["go"],
  "text/x-rust": ["rs"],
  "text/x-swift": ["swift"],
  "text/x-kotlin": ["kt", "kts"],
  "text/x-scala": ["scala"],
  "text/x-r": ["r"],
  "text/x-matlab": ["m"],
  "text/x-lua": ["lua"],
  "text/x-diff": ["diff", "patch"],
  "text/x-properties": ["properties"],
  "text/x-ini": ["ini", "cfg", "conf"],
  "text/x-toml": ["toml"],
  "text/x-dockerfile": ["dockerfile"],
  "text/x-makefile": ["makefile", "mk"],

  // ==================== APPLICATION FORMATS ====================
  "application/json": ["json"],
  "application/javascript": ["js", "mjs"],
  "application/typescript": ["ts"],
  "application/xml": ["xml", "xsl", "xsd", "wsdl", "soap"],
  "application/xhtml+xml": ["xhtml", "xht"],
  "application/rss+xml": ["rss"],
  "application/atom+xml": ["atom"],
  "application/soap+xml": ["soap"],
  
  // Archives & Compression
  "application/zip": ["zip", "zipx"],
  "application/x-rar-compressed": ["rar"],
  "application/x-7z-compressed": ["7z"],
  "application/x-tar": ["tar"],
  "application/gzip": ["gz", "gzip"],
  "application/x-bzip": ["bz"],
  "application/x-bzip2": ["bz2"],
  "application/x-lzip": ["lz"],
  "application/x-xz": ["xz"],
  "application/x-compress": ["z"],
  "application/x-ace-compressed": ["ace"],
  "application/x-alz-compressed": ["alz"],
  "application/x-arc-compressed": ["arc"],
  "application/x-arj": ["arj"],
  "application/x-cab": ["cab"],
  "application/x-lzh-compressed": ["lzh", "lha"],
  "application/x-stuffit": ["sit"],
  "application/x-stuffitx": ["sitx"],

  // Documents
  "application/pdf": ["pdf"],
  "application/postscript": ["ps", "eps", "ai"],
  "application/rtf": ["rtf"],
  "application/msword": ["doc"],
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"],
  "application/vnd.ms-excel": ["xls"],
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ["xlsx"],
  "application/vnd.ms-powerpoint": ["ppt"],
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": ["pptx"],
  "application/vnd.oasis.opendocument.text": ["odt"],
  "application/vnd.oasis.opendocument.spreadsheet": ["ods"],
  "application/vnd.oasis.opendocument.presentation": ["odp"],
  "application/vnd.oasis.opendocument.graphics": ["odg"],
  "application/vnd.oasis.opendocument.chart": ["odc"],
  "application/vnd.oasis.opendocument.formula": ["odf"],
  "application/vnd.oasis.opendocument.database": ["odb"],
  "application/vnd.oasis.opendocument.image": ["odi"],
  "application/vnd.sun.xml.writer": ["sxw"],
  "application/vnd.sun.xml.calc": ["sxc"],
  "application/vnd.sun.xml.impress": ["sxi"],
  "application/vnd.sun.xml.draw": ["sxd"],
  
  // Data formats
  "application/ld+json": ["jsonld"],
  "application/geo+json": ["geojson"],
  "application/vnd.api+json": ["json"],
  "application/hal+json": ["json"],
  "application/problem+json": ["json"],
  "application/x-ndjson": ["ndjson"],
  "application/x-jsonlines": ["jsonl"],
  "application/x-yaml": ["yaml", "yml"],
  "application/x-toml": ["toml"],
  "application/x-msgpack": ["msgpack"],
  "application/x-protobuf": ["proto", "pb"],
  "application/x-thrift": ["thrift"],
  "application/avro": ["avro"],
  "application/x-parquet": ["parquet"],
  "application/x-orc": ["orc"],
  
  // Executables & Binaries
  "application/octet-stream": ["bin", "exe", "dll", "so", "dylib", "deb", "rpm", "dmg", "pkg", "msi", "run", "deb", "AppImage"],
  "application/x-executable": ["exe", "bin", "run"],
  "application/x-msdos-program": ["exe", "com", "bat", "cmd"],
  "application/x-msdownload": ["exe", "dll", "com", "bat", "msi"],
  "application/x-debian-package": ["deb"],
  "application/x-redhat-package-manager": ["rpm"],
  "application/x-apple-diskimage": ["dmg"],
  "application/x-cd-image": ["iso"],
  "application/x-virtualbox-vdi": ["vdi"],
  "application/x-virtualbox-vhd": ["vhd"],
  "application/x-vmware-disk": ["vmdk"],
  
  // Web formats
  "application/x-www-form-urlencoded": ["url"],
  "application/x-httpd-php": ["php", "phtml"],
  "application/x-httpd-cgi": ["cgi"],
  "application/x-perl": ["pl", "pm"],
  "application/x-python-code": ["pyc", "pyo"],
  "application/x-shellscript": ["sh"],
  "application/x-sql": ["sql"],
  
  // Font formats
  "application/font-woff": ["woff"],
  "application/font-woff2": ["woff2"],
  "application/vnd.ms-fontobject": ["eot"],
  "application/x-font-ttf": ["ttf", "ttc"],
  "application/x-font-otf": ["otf"],
  "application/x-font-type1": ["pfa", "pfb", "pfm", "afm"],

  // E-book formats
  "application/epub+zip": ["epub"],
  "application/x-mobipocket-ebook": ["mobi", "prc"],
  "application/vnd.amazon.ebook": ["azw", "azw3"],
  "application/x-fictionbook+xml": ["fb2"],
  "application/x-sony-bbeb": ["lrf"],
  "application/x-ms-reader": ["lit"],

  // ==================== IMAGE FORMATS ====================
  "image/jpeg": ["jpg", "jpeg", "jpe", "jfif"],
  "image/png": ["png"],
  "image/gif": ["gif"],
  "image/webp": ["webp"],
  "image/svg+xml": ["svg", "svgz"],
  "image/tiff": ["tiff", "tif"],
  "image/bmp": ["bmp", "dib"],
  "image/x-icon": ["ico", "cur"],
  "image/vnd.microsoft.icon": ["ico"],
  "image/x-ms-bmp": ["bmp"],
  "image/x-portable-bitmap": ["pbm"],
  "image/x-portable-graymap": ["pgm"],
  "image/x-portable-pixmap": ["ppm"],
  "image/x-portable-anymap": ["pnm"],
  "image/x-xbitmap": ["xbm"],
  "image/x-xpixmap": ["xpm"],
  "image/x-pcx": ["pcx"],
  "image/x-tga": ["tga", "targa"],
  "image/x-sgi": ["sgi"],
  "image/x-sun-raster": ["ras"],
  "image/x-cmu-raster": ["ras"],
  "image/x-cmx": ["cmx"],
  "image/x-freehand": ["fh", "fhc", "fh4", "fh5", "fh7"],
  "image/x-photoshop": ["psd"],
  "image/vnd.adobe.photoshop": ["psd"],
  "image/x-gimp-xcf": ["xcf"],
  "image/x-gimp-gbr": ["gbr"],
  "image/x-gimp-pat": ["pat"],
  "image/x-gimp-gih": ["gih"],
  "image/heic": ["heic"],
  "image/heif": ["heif"],
  "image/avif": ["avif"],
  "image/jxl": ["jxl"],
  "image/jp2": ["jp2", "jpx", "j2k", "jpf"],
  "image/jpm": ["jpm"],
  "image/jpx": ["jpx"],

  // Raw image formats
  "image/x-canon-cr2": ["cr2"],
  "image/x-canon-crw": ["crw"],
  "image/x-epson-erf": ["erf"],
  "image/x-fuji-raf": ["raf"],
  "image/x-kodak-dcr": ["dcr"],
  "image/x-kodak-k25": ["k25"],
  "image/x-kodak-kdc": ["kdc"],
  "image/x-minolta-mrw": ["mrw"],
  "image/x-nikon-nef": ["nef"],
  "image/x-olympus-orf": ["orf"],
  "image/x-panasonic-raw": ["raw"],
  "image/x-pentax-pef": ["pef"],
  "image/x-sony-arw": ["arw"],
  "image/x-sony-sr2": ["sr2"],
  "image/x-sony-srf": ["srf"],
  "image/x-adobe-dng": ["dng"],

  // ==================== VIDEO FORMATS ====================
  "video/mp4": ["mp4", "m4v", "mp4v"],
  "video/webm": ["webm"],
  "video/ogg": ["ogv", "ogg"],
  "video/avi": ["avi"],
  "video/x-msvideo": ["avi"],
  "video/quicktime": ["mov", "qt"],
  "video/x-ms-wmv": ["wmv"],
  "video/x-ms-asf": ["asf"],
  "video/x-flv": ["flv"],
  "video/3gpp": ["3gp", "3gpp"],
  "video/3gpp2": ["3g2", "3gpp2"],
  "video/x-matroska": ["mkv", "mk3d", "mks"],
  "video/mp2t": ["ts", "mts", "m2ts"],
  "video/x-m4v": ["m4v"],
  "video/x-f4v": ["f4v"],
  "video/divx": ["divx"],
  "video/x-divx": ["divx"],
  "video/vnd.rn-realvideo": ["rv", "rmvb"],
  "video/x-pn-realvideo": ["rm", "rmvb"],
  "video/x-ms-vob": ["vob"],
  "video/dvd": ["vob"],
  "video/x-dv": ["dv"],
  "video/mp1s": ["m1s"],
  "video/mp2p": ["m2p"],
  "video/mp2v": ["m2v"],
  "video/mp4v-es": ["mp4v"],
  "video/mpeg": ["mpeg", "mpg", "mpe", "m1v", "m2v"],
  "video/h264": ["h264"],
  "video/h265": ["h265", "hevc"],
  "video/x-h264": ["h264"],
  "video/x-h265": ["h265"],

  // ==================== AUDIO FORMATS ====================
  "audio/mpeg": ["mp3", "mpga", "mp2", "mp2a", "m2a", "m3a"],
  "audio/mp4": ["m4a", "mp4a"],
  "audio/wav": ["wav"],
  "audio/wave": ["wav"],
  "audio/x-wav": ["wav"],
  "audio/ogg": ["oga", "ogg", "spx"],
  "audio/webm": ["weba"],
  "audio/aac": ["aac"],
  "audio/x-aac": ["aac"],
  "audio/flac": ["flac"],
  "audio/x-flac": ["flac"],
  "audio/opus": ["opus"],
  "audio/vorbis": ["ogg"],
  "audio/x-vorbis+ogg": ["ogg"],
  "audio/x-ms-wma": ["wma"],
  "audio/x-ms-wax": ["wax"],
  "audio/vnd.rn-realaudio": ["ra", "ram"],
  "audio/x-pn-realaudio": ["ra", "ram"],
  "audio/x-pn-realaudio-plugin": ["rmp"],
  "audio/x-realaudio": ["ra"],
  "audio/basic": ["au", "snd"],
  "audio/x-aiff": ["aif", "aiff", "aifc"],
  "audio/aiff": ["aif", "aiff", "aifc"],
  "audio/x-au": ["au"],
  "audio/x-gsm": ["gsm"],
  "audio/x-mpegurl": ["m3u"],
  "audio/x-scpls": ["pls"],
  "audio/midi": ["mid", "midi", "kar", "rmi"],
  "audio/x-midi": ["mid", "midi"],
  "audio/sp-midi": ["mid", "midi"],
  "audio/x-mod": ["mod", "s3m", "it", "xm"],
  "audio/s3m": ["s3m"],
  "audio/it": ["it"],
  "audio/xm": ["xm"],
  "audio/x-ape": ["ape"],
  "audio/x-monkeys-audio": ["ape"],
  "audio/x-wavpack": ["wv"],
  "audio/x-tta": ["tta"],
  "audio/x-musepack": ["mpc"],
  "audio/amr": ["amr"],
  "audio/amr-wb": ["awb"],
  "audio/evrc": ["evc"],
  "audio/evrc0": ["ev0"],
  "audio/evrc1": ["ev1"],
  "audio/evrcb": ["evb"],
  "audio/evrcb0": ["eb0"],
  "audio/evrcb1": ["eb1"],
  "audio/evrcnw": ["enw"],
  "audio/evrcnw0": ["en0"],
  "audio/evrcnw1": ["en1"],
  "audio/evrcwb": ["ewb"],
  "audio/evrcwb0": ["ew0"],
  "audio/evrcwb1": ["ew1"],

  // ==================== SPECIALIZED FORMATS ====================
  
  // 3D & CAD
  "model/obj": ["obj"],
  "model/gltf+json": ["gltf"],
  "model/gltf-binary": ["glb"],
  "model/iges": ["igs", "iges"],
  "model/mesh": ["msh", "mesh", "silo"],
  "model/stl": ["stl"],
  "model/vrml": ["wrl", "vrml"],
  "model/x3d+vrml": ["x3dv"],
  "model/x3d+xml": ["x3d"],
  "model/x3d+binary": ["x3db"],
  "application/sla": ["stl"],
  "application/x-3ds": ["3ds"],
  "application/x-blender": ["blend"],
  "application/x-maya": ["ma", "mb"],
  "application/x-cinema4d": ["c4d"],

  // Database
  "application/x-sqlite3": ["sqlite", "sqlite3", "db", "db3"],
  "application/x-msaccess": ["mdb", "accdb"],
  "application/x-dbf": ["dbf"],

  // Configuration
  "application/x-desktop": ["desktop"],
  "application/x-gnome-app-info": ["desktop"],
  "application/x-kde-app-info": ["desktop"],
  "text/x-systemd-unit": ["service", "socket", "device", "mount", "automount", "swap", "target", "path", "timer", "slice", "scope"],
  "application/x-wine-extension-inf": ["inf"],

  // Game files
  "application/x-nintendo-ds-rom": ["nds"],
  "application/x-gameboy-rom": ["gb"],
  "application/x-gameboy-color-rom": ["gbc"],
  "application/x-gba-rom": ["gba"],
  "application/x-genesis-rom": ["gen", "smd"],
  "application/x-n64-rom": ["n64", "z64"],
  "application/x-nes-rom": ["nes"],
  "application/x-snes-rom": ["smc", "sfc"],

  // Scientific
  "chemical/x-xyz": ["xyz"],
  "chemical/x-pdb": ["pdb"],
  "chemical/x-mol": ["mol"],
  "chemical/x-sdf": ["sdf"],
  "chemical/x-cml": ["cml"],
  "application/x-hdf": ["hdf"],
  "application/x-netcdf": ["nc", "cdf"],
  "application/fits": ["fits", "fit"],
  "application/x-tex": ["tex"],
  "application/x-latex": ["latex"],
  "application/x-bibtex": ["bib"],

  // Blockchain & Crypto
  "application/x-bitcoin-transaction": ["tx"],
  "application/x-bitcoin-block": ["blk"],
  "application/x-ethereum-transaction": ["ethtx"],
  "application/x-cryptocurrency-wallet": ["wallet", "dat"],

  // Miscellaneous
  "application/x-bittorrent": ["torrent"],
  "application/x-chrome-extension": ["crx"],
  "application/x-firefox-extension": ["xpi"],
  "application/vnd.android.package-archive": ["apk"],
  "application/x-ios-app": ["ipa"],
  "application/x-java-archive": ["jar"],
  "application/java-archive": ["jar"],
  "application/x-war": ["war"],
  "application/x-ear": ["ear"],
  "application/x-webarchive": ["webarchive"],
  "application/x-mhtml": ["mhtml", "mht"],
  "message/rfc822": ["eml"],
  "application/vnd.ms-outlook": ["msg"],
  "application/x-pkcs12": ["p12", "pfx"],
  "application/x-x509-ca-cert": ["crt", "cer", "der"],
  "application/x-pem-file": ["pem"],
  "application/pgp-keys": ["pgp", "gpg", "asc"],
  "application/pgp-signature": ["pgp", "sig"],
  "application/x-shockwave-flash": ["swf"],
  "application/vnd.adobe.air-application-installer-package+zip": ["air"],
  "application/x-ms-application": ["application"],
  "application/x-msclip": ["clp"],
  "application/x-mspublisher": ["pub"],
  "application/x-msmoney": ["mny"],
  "application/x-msmetafile": ["wmf", "emf"],
  "application/x-ms-shortcut": ["lnk"],
  "application/x-apple-alias": ["alias"],
  "application/mac-binhex40": ["hqx"],
  "application/x-macbinary": ["bin"],
  "application/x-sit": ["sit"],
  "application/x-gtar": ["gtar"],
  "application/x-ustar": ["ustar"],
  "application/x-cpio": ["cpio"],
  "application/x-shar": ["shar"],
  "application/x-bcpio": ["bcpio"],
  "application/x-sv4cpio": ["sv4cpio"],
  "application/x-sv4crc": ["sv4crc"],
  "application/x-csh": ["csh"],
  "application/x-tcl": ["tcl"],
  "application/x-tex-tfm": ["tfm"],
  "application/x-texinfo": ["texinfo", "texi"],
  "application/x-troff": ["t", "tr", "roff"],
  "application/x-troff-man": ["man"],
  "application/x-troff-me": ["me"],
  "application/x-troff-ms": ["ms"],
  "application/x-wais-source": ["src"]
};

// Helper function to get MIME type from file extension
export const getMimeTypeFromExtension = (extension: string): string => {
  const ext = extension.toLowerCase().replace(/^\./, '');
  
  for (const [mimeType, extensions] of Object.entries(supportedTypes)) {
    if (extensions.includes(ext)) {
      return mimeType;
    }
  }
  
  return 'application/octet-stream'; // Default fallback
};

// Helper function to get file extensions from MIME type
export const getExtensionsFromMimeType = (mimeType: string): string[] => {
  return supportedTypes[mimeType as keyof typeof supportedTypes] || [];
};

// Helper function to check if a MIME type is supported
export const isMimeTypeSupported = (mimeType: string): boolean => {
  return Object.prototype.hasOwnProperty.call(supportedTypes, mimeType);
};

// Helper function to get all supported extensions
export const getAllSupportedExtensions = (): string[] => {
  const extensions = new Set<string>();
  Object.values(supportedTypes).forEach(exts => {
    exts.forEach(ext => extensions.add(ext));
  });
  return Array.from(extensions).sort();
};

// Helper function to get MIME type category
export const getMimeTypeCategory = (mimeType: string): string => {
  const [primaryType] = mimeType.split('/');
  return primaryType;
};

// Export the main object
export default supportedTypes;